name = "Vault Hunters Modified"
author = "Eagy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "784abc02b3fc6187d1969dd1316ce9236ddb479691c7680a632f46ed8733c517"

[versions]
forge = "40.3.12"
minecraft = "1.18.2"
