name = "Vault Hunters Modified"
author = "Eagy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14f5fed0bf82d20a8dd3a255bc55688aa841a8c6a7f6010ee49b1c28839dad8e"

[versions]
forge = "40.3.12"
minecraft = "1.18.2"
