name = "Vault Hunters Modified"
author = "Eagy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3adeff23558940c4528a7808b66e6bb9f6113f7fe815fcec3ba46f1c159ff16a"

[versions]
forge = "40.3.12"
minecraft = "1.18.2"
